"""Use UUIDs and add constraints

Revision ID: c86a8df1bb28
Revises: 3b57a129b474
Create Date: 2026-02-08 00:33:56.191332

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c86a8df1bb28'
down_revision: Union[str, Sequence[str], None] = '3b57a129b474'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS pgcrypto")
    op.alter_column('comments', 'id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.UUID(),
               postgresql_using="id::uuid",
               server_default=sa.text("gen_random_uuid()"),
               existing_nullable=False)
    op.alter_column('comments', 'post_id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.UUID(),
               postgresql_using="post_id::uuid",
               existing_nullable=False)
    op.alter_column('comments', 'user_id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.UUID(),
               postgresql_using="user_id::uuid",
               existing_nullable=False)
    op.create_index(op.f('ix_comments_created_at'), 'comments', ['created_at'], unique=False)
    op.create_index(op.f('ix_comments_post_id'), 'comments', ['post_id'], unique=False)
    op.create_index(op.f('ix_comments_user_id'), 'comments', ['user_id'], unique=False)
    op.alter_column('messages', 'id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.UUID(),
               postgresql_using="id::uuid",
               server_default=sa.text("gen_random_uuid()"),
               existing_nullable=False)
    op.alter_column('messages', 'from_user_id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.UUID(),
               postgresql_using="from_user_id::uuid",
               existing_nullable=False)
    op.alter_column('messages', 'to_user_id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.UUID(),
               postgresql_using="to_user_id::uuid",
               existing_nullable=False)
    op.create_index(op.f('ix_messages_created_at'), 'messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_messages_from_user_id'), 'messages', ['from_user_id'], unique=False)
    op.create_index(op.f('ix_messages_to_user_id'), 'messages', ['to_user_id'], unique=False)
    op.alter_column('moderation_actions', 'id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.UUID(),
               postgresql_using="id::uuid",
               server_default=sa.text("gen_random_uuid()"),
               existing_nullable=False)
    op.alter_column('moderation_actions', 'actor_id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.UUID(),
               postgresql_using="actor_id::uuid",
               existing_nullable=False)
    op.alter_column('moderation_actions', 'target_post_id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.UUID(),
               postgresql_using="target_post_id::uuid",
               existing_nullable=False)
    op.create_index(op.f('ix_moderation_actions_actor_id'), 'moderation_actions', ['actor_id'], unique=False)
    op.create_index(op.f('ix_moderation_actions_created_at'), 'moderation_actions', ['created_at'], unique=False)
    op.create_index(op.f('ix_moderation_actions_target_post_id'), 'moderation_actions', ['target_post_id'], unique=False)
    op.alter_column('posts', 'id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.UUID(),
               postgresql_using="id::uuid",
               server_default=sa.text("gen_random_uuid()"),
               existing_nullable=False)
    op.alter_column('posts', 'owner_id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.UUID(),
               postgresql_using="owner_id::uuid",
               existing_nullable=False)
    op.create_index(op.f('ix_posts_created_at'), 'posts', ['created_at'], unique=False)
    op.create_index(op.f('ix_posts_owner_id'), 'posts', ['owner_id'], unique=False)
    op.alter_column('reports', 'id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.UUID(),
               postgresql_using="id::uuid",
               server_default=sa.text("gen_random_uuid()"),
               existing_nullable=False)
    op.alter_column('reports', 'post_id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.UUID(),
               postgresql_using="post_id::uuid",
               existing_nullable=False)
    op.alter_column('reports', 'reporter_id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.UUID(),
               postgresql_using="reporter_id::uuid",
               existing_nullable=False)
    op.create_index(op.f('ix_reports_created_at'), 'reports', ['created_at'], unique=False)
    op.create_index(op.f('ix_reports_post_id'), 'reports', ['post_id'], unique=False)
    op.create_index(op.f('ix_reports_reporter_id'), 'reports', ['reporter_id'], unique=False)
    op.alter_column('users', 'id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.UUID(),
               postgresql_using="id::uuid",
               server_default=sa.text("gen_random_uuid()"),
               existing_nullable=False)
    op.create_index(op.f('ix_users_city'), 'users', ['city'], unique=False)
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.drop_index(op.f('ix_users_city'), table_name='users')
    op.alter_column('users', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.drop_index(op.f('ix_reports_reporter_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_post_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_created_at'), table_name='reports')
    op.alter_column('reports', 'reporter_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('reports', 'post_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('reports', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.drop_index(op.f('ix_posts_owner_id'), table_name='posts')
    op.drop_index(op.f('ix_posts_created_at'), table_name='posts')
    op.alter_column('posts', 'owner_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('posts', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.drop_index(op.f('ix_moderation_actions_target_post_id'), table_name='moderation_actions')
    op.drop_index(op.f('ix_moderation_actions_created_at'), table_name='moderation_actions')
    op.drop_index(op.f('ix_moderation_actions_actor_id'), table_name='moderation_actions')
    op.alter_column('moderation_actions', 'target_post_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('moderation_actions', 'actor_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('moderation_actions', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.drop_index(op.f('ix_messages_to_user_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_from_user_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_created_at'), table_name='messages')
    op.alter_column('messages', 'to_user_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('messages', 'from_user_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('messages', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.drop_index(op.f('ix_comments_user_id'), table_name='comments')
    op.drop_index(op.f('ix_comments_post_id'), table_name='comments')
    op.drop_index(op.f('ix_comments_created_at'), table_name='comments')
    op.alter_column('comments', 'user_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('comments', 'post_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('comments', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    # ### end Alembic commands ###
